#!/bin/bash

#Calling a pattern with grep into holders file

grep -F 'Average loading absolute [mol/kg framework]' *.data  > sampleAd.txt
grep 'External Pressure' *.data > samplePr.txt

#Selecting data (didn't use)

#PRESSURE=$(awk -F' ' '{print $3}' samplePr.txt)
#UPTAKE=$(awk -F' ' '{print $7}' sampleAd.txt)
#ERROR=$(awk -F' ' '{ print $9 }' sampleAd.txt)

#Creating individual files by using awk
awk -F' ' '{print $3}' samplePr.txt > press
awk -F' ' '{print $7}' sampleAd.txt > upt
awk -F' ' '{ print $9 }' sampleAd.txt > err

echo -e "Pressure,Uptake,Error" > finaldata.csv
paste press upt err -d"," >> finaldata.csv
